### ISSUE TITLE
Missing example for docker-compose.yml

### ISSUE THREAD

**Issue by andreisusanu** [visibilityspots/dockerfile-cloudflared#19]
Missing example for docker-compose.yml

**Comment by andreisusanu** [comment]
Something like this, maybe:

```yml
version: '2'

services:
  cloudflared:
    image: visibilityspots/cloudflared
    container_name: cloudflared
    restart: always
    environment:
        DNS1: 1.1.1.1
        DNS2: 8.8.8.8
        PORT: 5053
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
```
