### ISSUE TITLE
Container Won't Start on Synology NAS

### ISSUE THREAD

**Issue by barndawgie** [visibilityspots/dockerfile-cloudflared#20]
I'm trying to start a container based on your image from Docker Hub using my Synology NAS, but it fails to startup everytime with the following error:

`Failed to open the metrics listener: listen tcp 192.64.119.253:0: bind: cannot assign requested address`

I'm using all of the default configurations with host networking. Is there some configuration I need to change?

**Comment by visibilityspots** [comment]
do you have more detailed logs? And which command do you use to start the container?

**Comment by Hobbabobba** [comment]
this `docker-compose.yml` started perfectly on my Synology NAS

```
version: '2'

services:
  cloudflared:
    image: visibilityspots/cloudflared
    container_name: cloudflared
    restart: always
    environment:
        DNS1: 1.1.1.1
        DNS2: 1.0.0.1
        PORT: 5054
    ports:
      - "5054:5054/tcp"
      - "5054:5054/udp"
```
