### ISSUE TITLE
Storing pihole config outside of container breaks cloudflared container

### ISSUE THREAD

**Issue by smholvoet** [visibilityspots/dockerfile-cloudflared#22]
I'm trying to use volumes in order to store pihole's config file outside of my container. This would allow me to easily upgrade my container whenever pihole's `latest` changes. See [this](https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose.yml.example) example from pihole's repo.

However, whenever I add the `volumes` section to my docker-compose file, it ends up breaking my cloudflared container. The container will keep on running and can't see anything weird in my container's logs, but DoH (DNS over HTTPS) stops working. I'm using https://1.1.1.1/help in order to verify this. As soon as I leave out the `volumes` section and re-run `docker-compose up`, everything works fine 🤷, which is driving me nuts.

My `docker-compose.yml` file:

```yml
version: "3.8"

services:
  cloudflared:
    image: visibilityspots/cloudflared:amd64
    container_name: cloudflared
    environment:
      TZ: '${TIMEZONE}'
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pi-hole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "80:80/tcp"
        - "443:443/tcp"
    environment:
      ServerIP: 10.0.0.3
      DNS1: '10.0.0.2#5054'
      DNS2: ''
      TZ: '${TIMEZONE}'
      DNSMASQ_LISTENING: all
      WEBPASSWORD: admin
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
```
